BillTrackerClient.App/Controllers/BillsController.cs
using BillTrackerClient.App.CoreModels;
using BillTrackerClient.App.Interfaces;
using BillTrackerClient.App.Models;
using BillTrackerClient.App.Models.PostModels;
using BillTrackerClient.App.Models.PostModels.UpdateModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BillTrackerClient.App.Controllers
{
    [Authorize]
    public class BillsController : ControllerHelper
    {
        private readonly IBillService _billService;
        private readonly ICompanyService _companyService;
        private readonly IMessageService _messageService;

        public BillsController(IBillService billService, ICompanyService companyService, IMessageService messageService)
        {
            _billService = billService;
            _companyService = companyService;
            _messageService = messageService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            var model = new PostBillViewModel
            {
                DateDue = DateTime.Now
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Add([FromBody] PostBillViewModel billModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (await _billService.BillNameExistsAsync(billModel.BillName, UserId))
                {
                    return BadRequest($"A bill with the name {billModel.BillName} aready exist");
                }

                var coreBill = new CoreBill(billModel, UserId)
                {
                    CompanyId = _companyService.GetCompanyIdByNameAsync(billModel.CompanyText)
                };

                await _billService.CreateBillAsync(coreBill);


                return OKMessage(_billService.BillCreatedMessage);
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        [HttpGet]
        public async Task<ActionResult> AllBills([FromQuery]int? index = null, string search = null)
        {

            var coreBills = await _billService.GetAllBillsAsync(UserId, index, search);
            var billModels = new List<BillViewModel>();

            if (coreBills.Count > 0)
            {
                for (int i = 0; i < coreBills.Count; i++)
                {
                    billModels.Add(new BillViewModel(coreBills[i]));
                }
            }

            return View(billModels);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateBill([FromBody] UpdateBillViewModel updateBillViewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                //TODO: Add a validation to check if bill belongs to user

                var coreBill = new CoreBill(updateBillViewModel, UserId)
                {
                    CompanyId = _companyService.GetCompanyIdByNameAsync(updateBillViewModel.CompanyText)
                };

                await _billService.UpdateBillAsync(coreBill);

                return OKMessage(_billService.BillUPdatedMessage);
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        [HttpPost]
        public async Task<ActionResult> ActiveBill([FromBody] PostActiveViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                await _billService.ActiveBillAsync(model.Id, model.IsActive);

                return OKMessage(_messageService.IsActiveMessage("bill", model.IsActive));
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }
    }
}

BillTrackerClient.App/Controllers/CompaniesController.cs
using BillTrackerClient.App.CoreModels;
using BillTrackerClient.App.Interfaces;
using BillTrackerClient.App.Models.PostModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net;
using System.Threading.Tasks;

namespace BillTrackerClient.App.Controllers
{
    [Authorize]
    public class CompaniesController : ControllerHelper
    {
        private readonly ICompanyService _companyService;

        public CompaniesController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        [HttpGet]
        public async Task<ActionResult> GetCompanyDropDown([FromQuery]string search, int? index = null)
        {
            var companyDropDown = await _companyService.GetCompanyDropDownAsync(search, index);

            if (companyDropDown.Count > 0)
            {
                return Ok(companyDropDown);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<ActionResult> AddCompany([FromBody] PostCompanyViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return NoContent();
                }

                var coreComment = new CoreCompany(model, UserId);

                await _companyService.AddCompanyAsync(coreComment);

                return OKMessage(_companyService.CompanyAddedOKMessage);
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }
    }
}

BillTrackerClient.App/Controllers/LoansController.cs
using BillTrackerClient.App.CoreModels;
using BillTrackerClient.App.Interfaces;
using BillTrackerClient.App.Models;
using BillTrackerClient.App.Models.PostModels;
using BillTrackerClient.App.Models.PostModels.UpdateModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BillTrackerClient.App.Controllers
{
    public class LoansController : ControllerHelper
    {
        #region Private fields
        private readonly ILoanService _loanService;
        private readonly ICompanyService _companyService;
        #endregion

        #region Constructors
        public LoansController(ILoanService loanService, ICompanyService companyService)
        {
            _loanService = loanService;
            _companyService = companyService;
        }
        #endregion

        #region View methods
        public ActionResult Add()
        {
            var model = new PostLoanViewModel
            {
                DateDue = DateTime.Now
            };

            return View(model);
        }

        public async Task<ActionResult> AllLoans([FromQuery] int? index = null, string search = null)
        {
            var coreLoans = await _loanService.GetAllLoansAsync(UserId, index, search);
            var loanViewModels = new List<LoanViewModel>();

            if (coreLoans.Count > 0)
            {
                for (int i = 0; i < coreLoans.Count; i++)
                {
                    loanViewModels.Add(new LoanViewModel(coreLoans[i]));
                }
            }

            return View(loanViewModels);

        }
        #endregion

        #region AJAX methods
        [HttpPost]
        public async Task<ActionResult> Add([FromBody] PostLoanViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _companyService.CompanyNameExistsAsync(model.CompanyText))
                {
                    return NotFound(_companyService.CompanyNameNotFoundMessage(model.CompanyText));
                }

                if (await _loanService.LoanExistsAsync(model.LoanName, UserId))
                {
                    return BadRequest(_loanService.LoanAlreadyExistsMessage(model.LoanName));
                }

                model.CompanyId = _companyService.GetCompanyIdByNameAsync(model.CompanyText);

                var coreLoan = new CoreLoan(model, UserId);

                await _loanService.AddLoanAsync(coreLoan);

                return OKMessage(_loanService.LoanCreatedOKMessage);
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Update([FromBody] UpdateLoanViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _companyService.CompanyNameExistsAsync(model.CompanyText))
                {
                    return NotFound(_companyService.CompanyNameNotFoundMessage(model.CompanyText));
                }

                if (await _loanService.LoanExistsAsync(model.LoanName, UserId, model.LoanId))
                {
                    return BadRequest(_loanService.LoanAlreadyExistsMessage(model.LoanName));
                }

                model.CompanyId = _companyService.GetCompanyIdByNameAsync(model.CompanyText);

                var coreLoan = new CoreLoan(model, UserId);

                await _loanService.UpdateLoanAsync(coreLoan);

                return OKMessage(new LoanViewModel(coreLoan, _loanService.LoanUpdatedOKMessage));
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        [HttpPost]
        public async Task<ActionResult> LoanIsActive([FromBody] PostActiveViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _loanService.UserOwnsLoanAsync(model.Id, UserId))
                {
                    return Unauthorized(UnAuthMessage);
                }

                await _loanService.ToggleLoanIsActive(model.Id, model.IsActive);

                return OKMessage(_loanService.LoanToggleMessage(model.IsActive));
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }
        #endregion
    }
}

BillTrackerClient.App/Controllers/SubscriptionsController.cs
using BillTrackerClient.App.CoreModels;
using BillTrackerClient.App.Interfaces;
using BillTrackerClient.App.Models;
using BillTrackerClient.App.Models.PostModels;
using BillTrackerClient.App.Models.PostModels.UpdateModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BillTrackerClient.App.Controllers
{
    [Authorize]
    public class SubscriptionsController : ControllerHelper
    {
        #region private fields
        private readonly ISubscriptionService _subscriptionService;
        private readonly ICompanyService _companyService;
        #endregion

        #region Constructors
        public SubscriptionsController(ISubscriptionService subscriptionService, ICompanyService companyService)
        {
            _subscriptionService = subscriptionService;
            _companyService = companyService;
        }
        #endregion

        #region View methods
        [HttpGet]
        public IActionResult Add()
        {
            var model = new PostSubscriptionViewModel
            {
                DateDue = DateTime.Now
            };

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> AllSubscriptions([FromQuery] int? index = null, string search = null)
        {
            var coreSubscriptions = await _subscriptionService.GetSubscriptionsAsync(UserId, index, search);
            var subscriptionViewModels = new List<SubscriptionViewModel>();

            if (coreSubscriptions.Count > 0)
            {
                for (int i = 0; i < coreSubscriptions.Count; i++)
                {
                    subscriptionViewModels.Add(new SubscriptionViewModel(coreSubscriptions[i]));
                }
            }

            return View(subscriptionViewModels);
        }
        #endregion

        #region AJAX methods
        [HttpPost]
        public async Task<ActionResult> Add([FromBody] PostSubscriptionViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _companyService.CompanyNameExistsAsync(model.CompanyText))
                {
                    return NotFound(_companyService.CompanyNameNotFoundMessage(model.CompanyText));
                }

                if (await _subscriptionService.SubscriptionExistsAsync(model.SubscriptionName, UserId))
                {
                    return BadRequest(_subscriptionService.SubscriptionAlreadyExistsMessage(model.SubscriptionName));
                }

                var coreSubscription = new CoreSubscription(model, UserId)
                {
                    CompanyId = _companyService.GetCompanyIdByNameAsync(model.CompanyText)
                };

                await _subscriptionService.AddSubscriptionAsync(coreSubscription);

                return OKMessage(_subscriptionService.SubscriptionCreatedOKMessage);

            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Update([FromBody] UpdateSubscriptionViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _companyService.CompanyNameExistsAsync(model.CompanyText))
                {
                    return NotFound(_companyService.CompanyNameNotFoundMessage(model.CompanyText));
                }

                model.CompanyId = _companyService.GetCompanyIdByNameAsync(model.CompanyText);

                if (!await _subscriptionService.UserOwnsSubscriptionAsync(model.SubscriptionId, UserId))
                {
                    return Unauthorized(UnAuthMessage);
                }

                if (await _subscriptionService.SubscriptionExistsAsync(model.SubscriptionName, UserId, model.SubscriptionId))
                {
                    return BadRequest(_subscriptionService.SubscriptionAlreadyExistsMessage(model.SubscriptionName));
                }

                var coreSubscription = new CoreSubscription(model, UserId);

                await _subscriptionService.UpdateSubscriptionAsync(coreSubscription);

                var viewModel = new SubscriptionViewModel(coreSubscription, _subscriptionService.SubscriptionUpdatedOKMessage);

                return OKMessage(viewModel);
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }

        public async Task<ActionResult> SubscriptionIsActive([FromBody] PostActiveViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(DisplayErrorMessages());
                }

                if (!await _subscriptionService.UserOwnsSubscriptionAsync(model.Id, UserId))
                {
                    return Unauthorized(UnAuthMessage);
                }

                await _subscriptionService.ToggleSubscriptionIsActive(model.Id, model.IsActive);

                return OKMessage(_subscriptionService.SubscriptionToggleMessage(model.IsActive));
            }
            catch (Exception e)
            {
                return InternalError(e);
            }
        }
        #endregion
    }
}

BillTrackerClient.App/Views/Shared/_CreateCompany.cshtml
<!--

The constant "successMessage" and "errorMessage" are declared in the _Layout view

-->

<div class="form-group">
    <div class="row">
        <div class="col-md-6">
            <input id="txtCompanySearch" class="form-control" placeholder="Enter a company text..." />
            <div id="companyDropdownItems" class="dropdown-div"></div>
        </div>
        <div class="col-md-6">
            <button id="btnAddCompany" class="btn btn-primary">Add a company</button>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/\jquery.min.js"></script>

<script type="text/javascript">
    const txtCompanySearch = document.getElementById('txtCompanySearch');
    const btnAddCompany = document.getElementById('btnAddCompany');
    const companyDropdownItems = document.getElementById('companyDropdownItems');

    var index = null;

    $(document).ready(function () {
        btnAddCompany.disabled = true;
    })

    txtCompanySearch.addEventListener('keyup', function (e) {
        e.preventDefault();

        if (txtCompanySearch.value !== '') {
            if ((e.key >= 'a' && e.key <= 'z') || e.key == 'Backspace') {
                companyDropdownItems.innerHTML = '';

                index = 0;

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetCompanyDropdown", "Companies")' + `?search=${txtCompanySearch.value}&index=${index}`,
                    success: function (data) {
                        companyDropdownItems.innerHTML = '';

                        for (let i = 0; i < data.length; i++) {
                            const element = data[i];
                            const div = document.createElement('div');
                            div.classList.add('dropdown-content-item', 'bg-secondary');
                            div.innerHTML = element.companyName;

                            div.addEventListener('click', function (e) {
                                e.preventDefault();

                                txtCompanySearch.value = element.companyName;

                                companyDropdownItems.innerHTML = '';
                            });

                            companyDropdownItems.appendChild(div);
                        }

                        btnAddCompany.disabled = true;
                    },
                    error: function (error) {
                        if (error.status != 404) {
                            errorMessage.innerText = error.responseText;
                        } else {
                            btnAddCompany.disabled = false;
                        }
                    }
                });
            }
        }
    });

    btnAddCompany.addEventListener('click', function (e) {
        e.preventDefault();

        let formData = {
            companyName: txtCompanySearch.value
        };

        $.ajax({
            type: 'POST',
            url: '@Url.Action("AddCompany", "Companies")',
            data: JSON.stringify(formData),
            contentType: 'application/json',
            dataType: "JSON",
            success: function (resp) {
                successMessage.innerHTML = resp;
                btnAddCompany.disabled = true;
            },
            error: function (err) {
                errorMessage.innerHTML = err.responseText;
            }
        });
    });
</script>

BillTrackerClient.App/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

@{ 
    string appName = "Expense Tracker";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @appName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@appName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#billDropdown" aria-controls="billDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="billDropdown">
                                    <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Bills
                                            </a>
                                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Bills" asp-action="Add">Add a bill</a>
                                                </li>

                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Bills" asp-action="AllBills">My bills</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#subscriptionDropdown" aria-controls="subscriptionDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>

                                <div class="collapse navbar-collapse" id="subscriptionDropdown">
                                    <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Subscriptions
                                            </a>
                                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Subscriptions" asp-action="Add">Add a subscriptions</a>
                                                </li>

                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Subscriptions" asp-action="AllSubscriptions">My subscriptions</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#loansDropdown" aria-controls="loansDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>

                                <div class="collapse navbar-collapse" id="loansDropdown">
                                    <ul class="navbar-nav">
                                        <li class="nav-item dropdown">
                                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                Loans
                                            </a>
                                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Loans" asp-action="Add">Add a Loan</a>
                                                </li>

                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Loans" asp-action="AllLoans">My loans</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <p id="errorMessage" class="text-danger font-weight-bold">@ViewBag.error</p>
            <p id="successMessage" class="text-success font-weight-bold">@ViewBag.success</p>
            <ul id="errorList" class="text-danger"></ul>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @appName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="/lib/jquery/dist/jquery.js"></script>    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/GlobalFunctions.js"></script>
    <script type="text/javascript">
        const successMessage = document.getElementById('successMessage');
        const errorMessage = document.getElementById('errorMessage')
        const errorList = document.getElementById('errorList')
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>